/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    BaseButton: typeof import('./src/components/base-button.vue')['default']
    BaseI18nSelector: typeof import('./src/components/base-i18n-selector.vue')['default']
    BaseLogo: typeof import('./src/components/base-logo.vue')['default']
    BasePagination: typeof import('./src/components/base-pagination.vue')['default']
    CardCourse: typeof import('./src/components/card-course.vue')['default']
    LayoutContainer: typeof import('./src/components/layout-container.vue')['default']
    LayoutCourse: typeof import('./src/components/layout-course.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
